#!/bin/bash
echo "Generating cert files...";
openssl req -x509 -nodes -batch -newkey rsa:2048 -keyout ./horizon-key.pem -out ./horizon-cert.pem -days 365 > /dev/null 2> /dev/null &&
mkdir -p /etc/trailbot-vault &&
mv ./horizon-*.pem /etc/trailbot-vault/ -f &&
(
echo "project_name = \"trailbot_vault\""      > /etc/trailbot-vault/horizon.toml
echo "key_file = \"/srv/horizon-key.pem\""   >> /etc/trailbot-vault/horizon.toml
echo "cert_file = \"/srv/horizon-cert.pem\"" >> /etc/trailbot-vault/horizon.toml
echo "allow_anonymous = true"                >> /etc/trailbot-vault/horizon.toml
echo "allow_unauthenticated = false"         >> /etc/trailbot-vault/horizon.toml
echo "token_secret = \"CHZcXtuK+psL1Ci/IIEOhgg0N/MYbGyrZqwQGmj8VyUOrc+fNhaGo+CCEGienEIpt/yY/enuBCRqFdgdpTcJJw==\"" >> /etc/trailbot-vault/horizon.toml
) &&
cp ./schema.toml /etc/trailbot-vault/ &&
echo "Setting schema...";
mkdir .hz;
hz set-schema /etc/trailbot-vault/schema.toml --force --config /etc/trailbot-vault/horizon.toml
