#!/bin/bash
if ! [ `which rethinkdb` ]
then
  echo -e "\e[01;31mERROR: RethinkDB is not installed\e[0m"
  echo "Please go to http://rethinkdb.com/docs/install/ for downloads and installation instructions."
  exit
fi
echo "Generating cert files...";
openssl req -x509 -nodes -batch -newkey rsa:2048 -keyout ./horizon-key.pem -out ./horizon-cert.pem -days 365 &&
mkdir -p /etc/trailbot-vault 2> /dev/null &&
mv ./horizon-*.pem /srv/ -f &&
(
cat > /etc/trailbot-vault/horizon.toml <<-EOM
project_name = "trailbot_vault"
key_file = "/srv/horizon-key.pem"
cert_file = "/srv/horizon-cert.pem"
allow_anonymous = true
token_secret = "$(head -c56 /dev/urandom | base64)"
start_rethinkdb = true
serve_static = "./dist"
bind = ["0.0.0.0"]
EOM
) &&
cp ./schema.toml /etc/trailbot-vault/ &&
(
if [ `which systemd` ]
then
cat > /etc/systemd/system/trailbot-vault.service <<- EOM
[Unit]
Description=Trailbot Vault
After=network.target

[Service]
ExecStart=$(pwd)/start
ExecStop=$(pwd)/stop
Restart=always
User=root
Group=root
WorkingDirectory=$(pwd)

[Install]
WantedBy=multi.user.target
EOM
systemctl enable trailbot-vault
else
cat > /etc/init/trailbot-vault.conf <<- EOM
#!upstart
description "Trailbot Vault"

respawn

start on (local-filesystems and net-device-up IFACE!=lo)
stop on shutdown

script
  chdir $(pwd)
  exec $(pwd)/start
end script
EOM
chmod +x /etc/init/trailbot-vault.conf
fi
) &&
service trailbot-vault start
echo "Setting schema...";
mkdir .hz 2> /dev/null;
hz set-schema /etc/trailbot-vault/schema.toml --force --config /etc/trailbot-vault/horizon.toml &&
echo "Trailbot Vault is now up and running!"
